version: '3'
services:
  backend_oezendev_db:
    build:
      context: ./psql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    backend:
      container
volumes:
  database-data:
